<?php
define("DB_HOST",'localhost');
define("DB_USER",'root');
define("DB_PWD",'');
define("DB_NAME",'pd_school');
define("DB_PORT",'3306');
define("DB_TYPE",'mysql');
define("DB_CHARSET",'utf8');
define("WEB_NAME",'我的学校');
